# Generated by Django 2.1.3 on 2019-06-05 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20190605_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Item'),
        ),
    ]
