# Generated by Django 2.1.3 on 2019-06-05 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20190605_2013'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buyer',
            options={},
        ),
    ]
