# Generated by Django 2.1.3 on 2019-06-05 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20190605_2031'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buyer',
            options={'verbose_name': 'バイヤー', 'verbose_name_plural': 'バイヤー'},
        ),
    ]
