# Generated by Django 2.1.3 on 2019-06-06 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20190605_2034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyer',
            name='item',
        ),
        migrations.AddField(
            model_name='item',
            name='bought_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Buyer', to_field='buyername'),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='buyername',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
