# Generated by Django 2.1.3 on 2019-06-06 10:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_remove_buyer_registered_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='registered_by',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
