# Generated by Django 2.1.3 on 2019-06-06 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_buyer_registered_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buyer',
            old_name='registered_by',
            new_name='related_user',
        ),
    ]
