# Generated by Django 2.1.3 on 2019-06-06 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20190606_1904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyer',
            name='related_user',
        ),
    ]
