# Generated by Django 2.1.3 on 2019-06-06 10:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_remove_buyer_related_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='related_user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
