# Generated by Django 2.1.3 on 2019-07-25 10:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_buyer_related_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyer',
            name='adress',
        ),
        migrations.RemoveField(
            model_name='buyer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='buyer',
            name='related_user',
        ),
        migrations.AddField(
            model_name='buyer',
            name='related_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
